name: learn-github-actions-deepseek
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
permissions:
  pull-requests: write

jobs:
  # setup-deepseek-review:
  #   runs-on: ubuntu-latest
  #   name: Code Review
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: DeepSeek Code Review
  #       uses: hustcer/deepseek-review@v1
  #       with:
  #         chat-token: sk-912721c3ef0540e7a7615e430c33e709

  setup-deepseek-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: sk-912721c3ef0540e7a7615e430c33e709