name: learn-github-actions-deepseek
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request_target:
    types:
      - opened      # Triggers when a PR is opened
      - reopened    # Triggers when a PR is reopened
      - synchronize # Triggers when a commit is pushed to the PR
permissions:
  pull-requests: write

jobs:
   setup-deepseek-review:
     runs-on: ubuntu-latest
     name: Code Review
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 2
       - name: DeepSeek Code Review
         uses: hustcer/deepseek-review@v1
         with:
           chat-token: ${{ DS_SECRET }}
           exclude-patterns: "*.md, *.txt"
           max-length: 2000
           temperature: 0.7