name: learn-github-actions-deepseek
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request_target:
    types:
      - opened      # Triggers when a PR is opened
      - reopened    # Triggers when a PR is reopened
      - synchronize # Triggers when a commit is pushed to the PR
permissions:
  pull-requests: write

jobs:
   setup-deepseek-review:
       - name: DeepSeek Code Review
         uses: hustcer/deepseek-review@v1
         with:
           chat-token: sk-912721c3ef0540e7a7615e430c33e709
           exclude-patterns: "*.md, *.txt"
           max-length: 2000
           temperature: 0.7

#  setup-deepseek-review:
#    runs-on: ubuntu-latest
#    name: Code Review
#    steps:
#      - name: DeepSeek Code Review
#        uses: hustcer/deepseek-review@v1
#        with:
#          chat-token: sk-912721c3ef0540e7a7615e430c33e709